// This file is auto-generated by: npm run supabase:gen-types
// Do not edit manually - it will be overwritten

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          preferences: Json;
          storage_used_bytes: number;
          storage_limit_bytes: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          preferences?: Json;
          storage_used_bytes?: number;
          storage_limit_bytes?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          preferences?: Json;
          storage_used_bytes?: number;
          storage_limit_bytes?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      books: {
        Row: {
          id: string;
          owner_id: string;
          title: string;
          authors: string[];
          description: string | null;
          language: string;
          isbn: string | null;
          publisher: string | null;
          published_date: string | null;
          file_type: string;
          storage_path: string;
          file_size_bytes: number;
          page_count: number | null;
          source: string;
          source_url: string | null;
          source_metadata: Json;
          text_content: string | null;
          text_indexed: unknown | null;
          thumbnail_url: string | null;
          cover_color: string;
          metadata_json: Json;
          tags: string[];
          processing_status: string;
          processing_error: string | null;
          created_at: string;
          updated_at: string;
          last_opened_at: string | null;
        };
        Insert: {
          id?: string;
          owner_id: string;
          title: string;
          authors?: string[];
          description?: string | null;
          language?: string;
          isbn?: string | null;
          publisher?: string | null;
          published_date?: string | null;
          file_type: string;
          storage_path: string;
          file_size_bytes: number;
          page_count?: number | null;
          source?: string;
          source_url?: string | null;
          source_metadata?: Json;
          text_content?: string | null;
          thumbnail_url?: string | null;
          cover_color?: string;
          metadata_json?: Json;
          tags?: string[];
          processing_status?: string;
          created_at?: string;
          updated_at?: string;
          last_opened_at?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string;
          title?: string;
          authors?: string[];
          description?: string | null;
          language?: string;
          isbn?: string | null;
          publisher?: string | null;
          published_date?: string | null;
          file_type?: string;
          storage_path?: string;
          file_size_bytes?: number;
          page_count?: number | null;
          source?: string;
          source_url?: string | null;
          source_metadata?: Json;
          text_content?: string | null;
          thumbnail_url?: string | null;
          cover_color?: string;
          metadata_json?: Json;
          tags?: string[];
          processing_status?: string;
          processing_error?: string | null;
          updated_at?: string;
          last_opened_at?: string | null;
        };
      };
      annotations: {
        Row: {
          id: string;
          book_id: string;
          user_id: string;
          page: number;
          coords: Json;
          type: string;
          color: string;
          opacity: number;
          thickness: number;
          selected_text: string | null;
          content: string | null;
          drawing_data: Json | null;
          device_id: string | null;
          crdt_state: Json | null;
          version: number;
          synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          book_id: string;
          user_id: string;
          page: number;
          coords: Json;
          type: string;
          color?: string;
          opacity?: number;
          thickness?: number;
          selected_text?: string | null;
          content?: string | null;
          drawing_data?: Json | null;
          device_id?: string | null;
          crdt_state?: Json | null;
          version?: number;
          synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          book_id?: string;
          user_id?: string;
          page?: number;
          coords?: Json;
          type?: string;
          color?: string;
          opacity?: number;
          thickness?: number;
          selected_text?: string | null;
          content?: string | null;
          drawing_data?: Json | null;
          device_id?: string | null;
          crdt_state?: Json | null;
          version?: number;
          synced_at?: string | null;
          updated_at?: string;
        };
      };
      bookmarks: {
        Row: {
          id: string;
          book_id: string;
          user_id: string;
          page: number;
          scroll_offset: number;
          location_json: Json;
          progress_percent: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          book_id: string;
          user_id: string;
          page: number;
          scroll_offset?: number;
          location_json?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          book_id?: string;
          user_id?: string;
          page?: number;
          scroll_offset?: number;
          location_json?: Json;
          updated_at?: string;
        };
      };
      collections: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          color: string;
          icon: string | null;
          parent_id: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          color?: string;
          icon?: string | null;
          parent_id?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          color?: string;
          icon?: string | null;
          parent_id?: string | null;
          sort_order?: number;
          updated_at?: string;
        };
      };
    };
    Views: {};
    Functions: {
      search_books: {
        Args: {
          search_query: string;
          user_id_filter: string;
          result_limit?: number;
        };
        Returns: {
          book_id: string;
          title: string;
          authors: string[];
          thumbnail_url: string | null;
          match_snippet: string;
          rank: number;
        }[];
      };
    };
    Enums: {};
  };
}
