# Prometheus Configuration for OmniQuant

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'omniquant-prod'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Load alert rules
rule_files:
  - '/etc/prometheus/alerts/*.yml'

# Scrape configurations
scrape_configs:
  # OmniQuant API metrics
  - job_name: 'omniquant-api'
    static_configs:
      - targets: ['api:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL metrics (if exporter installed)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics (if exporter installed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node metrics (if node exporter installed)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
