"""
OmniQuant Strategy CLI - scaffolding tool for new strategies.

Usage:
    python -m src.cli new-strategy
    python -m src.cli new-strategy --name PairsReversion --author "Jane Doe"
"""

from __future__ import annotations

import re
import textwrap
from pathlib import Path

try:
    import typer
except ImportError:
    raise SystemExit(
        "typer is not installed. Run: pip install typer\n"
        "Or:  pip install -r requirements-dev.txt"
    )

app = typer.Typer(help="OmniQuant developer CLI")

STRATEGY_TEMPLATE = textwrap.dedent('''\
    """
    {class_name} Strategy
    Auto-generated by `python -m src.cli new-strategy`

    Author: {author}
    """

    from __future__ import annotations

    from typing import Any, Dict, Optional

    import pandas as pd
    from loguru import logger

    from .base_strategy import BaseStrategy


    class {class_name}(BaseStrategy):
        """
        {class_name} - TODO: describe your strategy here.
        """

        def __init__(self, config: Optional[Dict[str, Any]] = None) -> None:
            super().__init__("{class_name}", config)
            # TODO: extract your parameters from self.config
            self.lookback = self.config.get("lookback", 20)

        def initialize(self, simulator: Any) -> None:
            """Called once before the backtest loop starts."""
            self.is_initialized = True
            logger.info(f"{{self.name}} initialised")

        def on_data(self, simulator: Any, symbol: str, data: pd.Series) -> None:
            """Called on every market data tick."""
            current_price = data.get("close", data.get("price"))
            if current_price is None:
                return

            # ------------------------------------------------------------
            # TODO: implement your signal logic here
            # Example:
            #   if signal > threshold:
            #       simulator.buy(symbol, 100)
            # ------------------------------------------------------------
            pass

        def finalize(self, simulator: Any) -> None:
            """Called after the backtest loop finishes."""
            logger.info(f"{{self.name}} finalised")
''')

STRATEGIES_DIR = Path(__file__).resolve().parent / "strategies"


def _to_snake(name: str) -> str:
    """CamelCase → snake_case"""
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


@app.command()
def new_strategy(
    name: str = typer.Option("MyStrategy", "--name", "-n", help="CamelCase class name"),
    author: str = typer.Option("OmniQuant Developer", "--author", "-a", help="Author name"),
) -> None:
    """Generate a new strategy file from template."""
    filename = _to_snake(name) + ".py"
    filepath = STRATEGIES_DIR / filename

    if filepath.exists():
        typer.echo(f"Error: {filepath} already exists. Choose a different name.")
        raise typer.Exit(code=1)

    content = STRATEGY_TEMPLATE.format(class_name=name, author=author)
    filepath.write_text(content, encoding="utf-8")
    typer.echo(f"Created {filepath.relative_to(Path.cwd())}")
    typer.echo(f"  class {name}(BaseStrategy)  in  {filename}")
    typer.echo("Open the file and fill in the TODO sections.")


@app.command()
def list_strategies() -> None:
    """List all strategy files."""
    for p in sorted(STRATEGIES_DIR.glob("*.py")):
        if p.name.startswith("__"):
            continue
        typer.echo(f"  {p.name}")


if __name__ == "__main__":
    app()
